# encoding: utf-8

# Constants used in the library.
module Rlp
  FLEXEME_TYPES = {
    :subst => "Rlp::Flexeme::Noun",
    :depr => "Rlp::Flexeme::DepreciativeNoun",
    :sdef => "Rlp::Flexeme::DefectiveNoun",
    :xxs => "Rlp::Flexeme::ForeignNominal",
    :adj => "Rlp::Flexeme::Adjective",
    :adjng => "Rlp::Flexeme::NonGradableAdjective",
    :adja => "Rlp::Flexeme::PreadjectivalAdjective",
    :adjp => "Rlp::Flexeme::PostprepositionalAdjective",
    :adjdef => "Rlp::Flexeme::DefectiveAdjective",
    :adv => "Rlp::Flexeme::Adverb",
    :advdef => "Rlp::Flexeme::DefectiveAdverb",
    :fin => "Rlp::Flexeme::NonpastVerb",
    :bedzie => "Rlp::Flexeme::FutureVerb",
    :aglt => "Rlp::Flexeme::AglutinativeVerb",
    :acond => "Rlp::Flexeme::AgultinativeConditional",
    :praet => "Rlp::Flexeme::PastVerb",
    :impt => "Rlp::Flexeme::ImperativeMoodVerb",
    :imps => "Rlp::Flexeme::ImpersonalMoodVerb",
    :inf => "Rlp::Flexeme::InfinitiveVerb",
    :pcon => "Rlp::Flexeme::PresentParticiple",
    :pant => "Rlp::Flexeme::PerfectParticiple",
    :pact => "Rlp::Flexeme::ActiveParticiple",
    :ppas => "Rlp::Flexeme::PassiveParticiple",
    :ger => "Rlp::Flexeme::Gerund",
    :imptdef => "Rlp::Flexeme::ImperativeVerb",
    :anl => "Rlp::Flexeme::AnalyticVerb",
    :impsdef => "Rlp::Flexeme::ImpersonalVerb",
  }

  FLEXEME_NAMES = {
    :subst => "rzeczownik",
    :depr => "rzeczownik deprecjatywny",
    :sdef => "rzeczownik defektywny",
    :xxs => "ciało obce nominalne",
    :adj => "przymiotnik",
    :adjng => "przymiotnik niestopniowalny",
    :adja => "przymiotnik przyprzymiotnikowy",
    :adjp => "przymiotnik poprzyimkowy",
    :adjdef => "przymiotnik nieodmienny",
    :adv => "przysłówek",
    :advdef => "przysłówek nieodmienny",
    :fin => "forma nieprzeszła",
    :bedzie => "forma przyszła czasownika BYĆ",
    :aglt => "aglutynant czasownika BYĆ",
    :acond => "aglutynant trybu przypuszczającego",
    :praet => "pseudoimiesłów",
    :impt => "rozkaźnik",
    :imps => "bezosobnik",
    :inf => "bezokolicznik",
    :pcon => "imiesłów przysłówkowy współczesny",
    :pant => "imiesłów przysłówkowy uprzedni",
    :pact => "imiesłów przymiotnikowy czynny",
    :ppas => "imiesłów przymiotnikowy bierny",
    :ger => "odsłownik",
    :imptdef => "czasownik imperatywny",
    :anl => "czasownik analityczny",
    :impsdef => "czasownik nieosobowy",
  }
  CATEGORY_NAMES = {
    :case => "przypadek",
    :gender => "rodzaj",
    :number => "liczba",
    :person => "osoba",
    :degree => "stopień",
    :aspect => "aspekt",
    :accent => "akcentowość",
    :pospre => "poprzyimkowość",
    :accomm => "akomodacyjność",
    :agglut => "aglutynacyjność",
    :vocal => "wokaliczność",
    :lcase => "kasztowość"
  }
end
